### PR TITLE
 fixed naming conflict with AnimatedItemBuilder from SDK

### PR DESCRIPTION
**Pull request by xpointsolution**
When trying to compile with flutter 3.7.0 for iOS following error prevents the app from being built successfully. 

`Error (Xcode): ../../../.pub-cache/hosted/pub.dev/implicitly_animated_reorderable_list-0.4.2/lib/src/implicitly_animated_reorderable_list.dart:8:1: Error: 'AnimatedItemBuilder' is imported from both 'package:flutter/src/widgets/animated_scroll_view.dart' and 'package:implicitly_animated_reorderable_list/src/implicitly_animated_list_base.dart'.`

The issue is caused by `AnimatedItemBuilder` being exported from `package:flutter/material.dart`. 

In this PR custom `AnimatedItemBuilder` is renamed to `ImplicitlyAnimatedItemBuilder` to avoid possible naming conflicts.

### CODE REVIEW

**Comment by gtalha07** [comment]
Cool! When are we expecting this to be merged on upstream? We have automated CIs which are failing tests just because of this reason and blocking the merges.

**Comment by theniceboy** [comment]
Sorry I must have missed this. Merging

**Comment by theniceboy** [comment]
0.5.0 live on pub.dev

Thank you for the PR! @xpointsolution

**Comment by rafaelsetragni** [comment]
I also checked the changes in the files and tested it in my local project. Its all good and fixed the issue with AnimatedItemBuilder' imported from multiple packages. This change is totally necessary for Flutter 3.7.

**Pull request merged**
