### PR TITLE
Fixed project to run with flutter 3.22

### PR DESCRIPTION
**Pull request by xpointsolution**

### CODE REVIEW

**Comment by K123Ritesh** [comment]
@theniceboy  Merge this ASAP My app crashed due to this version update of flutter

**Comment by theniceboy** [comment]
Thanks for the PR!

Quick question: Why are some of the classes renamed? (e.g. `AnimatedListRemovedItemBuilder` -> `AnimatedRemovedItemBuilder`). This might cause some breaking changes.

**Comment by temcewen** [comment]
@theniceboy `AnimatedListItemBuilder` and `AnimatedListRemovedItemBuilder`  has been removed from Flutter which is the main issue this solves as far as I can see. It's definitely something that needs to be merged, this package broke our project as well because of the issue this pull request fixes.

**Comment by theniceboy** [comment]
Thanks!

**Comment by theniceboy** [comment]
0.6.0 published

**Pull request merged**
